# Generated by Django 6.0.2 on 2026-03-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_db',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
