# Generated by Django 6.0.2 on 2026-03-10 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_db_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_db',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
